name: CI/CD

# on: [push, pull_request]
on:
  push:
    branches:
      - narnia

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

  #     - name: Get yarn cache directory path ğŸ› 
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn cache dir)"

  #     - name: Cache node_modules ğŸ“¦
  #       uses: actions/cache@v2.1.4
  #       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-

  #     - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
  #       run: yarn

  #     - name: Run linter ğŸ‘€
  #       run: yarn lint

  # cd:
  #   runs-on: ${{ matrix.os }}
  #   needs: [ci]

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       node: [14]

  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Setup node env
  #       uses: actions/setup-node@v2.1.2
  #       with:
  #         node-version: ${{ matrix.node }}

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Generate
  #       run: yarn run generate

  #     - name: Deploy
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist
